Repository jfrog/artifactory-gradle-plugin, pull requests merged in 2023-09, with the labels that each got.

#66 docs: wrong settings of publishBuildInfo
  README.md
Labels: ignore for release

#68 Update build-info to 2.41.5
  build.gradle.kts
Labels: improvement

#70 afterEvaluate runs when project is already evaluated
  src/main/java/org/jfrog/gradle/plugin/artifactory/ArtifactoryPlugin.java
Labels: bug
