Repository jfrog/artifactory-gradle-plugin, pull requests merged in 2023-07, with the labels that each got.

#32 Support setting the context URL
  src/main/java/org/jfrog/gradle/plugin/artifactory/config/ArtifactoryPluginConvention.java
Labels: bug

#33 Fix Publish to Gradle gallery
  build.gradle.kts
  src/main/java/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
Labels: ignore for release

#23 Readme Improvements
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/frogbot-scan-and-fix.yml
  README.md
Labels: ignore for release

#34 Publish to Gradle - action changes
  .github/workflows/gradle.yml
Labels: ignore for release

#36 Removing class path breaking change
  src/functionalTest/resources/gradle-kts-example-publish/build.gradle.kts
  src/main/java/org/jfrog/gradle/plugin/artifactory/ArtifactoryPlugin.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/dsl/ArtifactoryPluginConvention.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/dsl/PropertiesConfig.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/dsl/PublisherConfig.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/extractor/GradleDeployDetails.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/extractor/GradleModuleExtractor.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/extractor/PublishArtifactInfo.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/listener/ProjectsEvaluatedBuildListener.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/utils/ConventionUtils.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/utils/DeployUtils.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/utils/ProjectUtils.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/utils/PublicationUtils.java
  src/test/java/org/jfrog/gradle/plugin/artifactory/PropertiesConfigTest.java
Labels: bug

#39 Update plugin publish plugin to v1
  build.gradle.kts
Labels: bug

#40 Disable PluginMarker publication
  build.gradle.kts
Labels: ignore for release

#41 Add validatePlugins to tests and release
  .github/workflows/test.yml
  .jfrog-pipelines/release/pipelines.release.yml
  .jfrog-pipelines/release/pipelines.snapshot.yml
Labels: ignore for release

#37 Task configurations avoidance
  src/main/java/org/jfrog/gradle/plugin/artifactory/ArtifactoryPlugin.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/task/ArtifactoryTask.java
  src/main/java/org/jfrog/gradle/plugin/artifactory/utils/TaskUtils.java
  src/main/resources/initscripttemplate.gradle
Labels: improvement
